apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : myapp1
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ~v0.4
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: app1
  source:
    path   : "HelmCharts/MyChart1"
    repoURL: "https://github.com/freeman9917/argocd.git"
    targetRevision: HEAD
    helm:
      parameters:
      - name: "container.image"
        value: 013273876354.dkr.ecr.eu-central-1.amazonaws.com/my-ecr
      - name: "container.tag"
        value: v0.1.0

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true         
