apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: my-app
          image: 548844171305.dkr.ecr.ap-south-1.amazonaws.com/brainscale-ecr:latest
          ports:
          - containerPort: 3000
