apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
