helm:
  parameters:
  - name: image.repository
    value: 013273876354.dkr.ecr.eu-central-1.amazonaws.com/my-ecr
    forcestring: false
  - name: image.tag
    value: v0.4.1
    forcestring: true
  - name: image.name
    value: 013273876354.dkr.ecr.eu-central-1.amazonaws.com/my-ecr
    forcestring: true
